### ISSUE TITLE
Configure copybutton_prompt_text to support multiple prompt types

### ISSUE THREAD

**Issue by lukelbd** [executablebooks/sphinx-copybutton#81] opened 2020-05-31 20:37 UTC
Is there any way to configure `copybutton_prompt_text` to support multiple prompt types?

For example, a simple python interpreter example with multi-line input:

```python
>>> for i in range(3):
...     for j in range(3):
...         print(i * j)
0
0
0
0
1
2
0
2
4
```

Or an ipython test:

```python
In [1]: a = 'foobar'
   ...: a
Out [1]:'foo'
```

How can I get this extension to remove the "In", "Out", ">>>", and ellipsis style prompts?

**Comment by choldgraf** [comment] 2020-06-01 03:28
Agreed - this would be useful! I think it's actually a dupe of https://github.com/executablebooks/sphinx-copybutton/issues/52 so I'll close this in favor of that one. Feel free to chime in there!

**Closed by choldgraf** 2020-06-01 03:28 UTC
